// Re-export from virtual:brand module generated by vite-plugin-brand.
// This file exists so imports resolve cleanly via '@/' alias.
// Types (NavItem, LogoConfig, BrandConfig) are globally declared in vite-env.d.ts.
export {
  brandName,
  tagline,
  accent,
  logo,
  favicon,
  colors,
  header,
  sidebar,
} from 'virtual:brand';
